import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: "GitIt",
    projects: ProjectName.allCases.map(\.projectPath),
    schemes: [ProjectName.allTestsScheme],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled
    ),
)
